# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ecc.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_btn_sign(object):
    def setupUi(self, btn_sign):
        btn_sign.setObjectName("btn_sign")
        btn_sign.resize(937, 522)
        self.centralwidget = QtWidgets.QWidget(btn_sign)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(380, 70, 55, 16))
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(370, -20, 241, 101))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 90, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 260, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.txt_information = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_information.setGeometry(QtCore.QRect(250, 110, 511, 91))
        self.txt_information.setObjectName("txt_information")
        self.txt_signature = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_signature.setGeometry(QtCore.QRect(250, 270, 511, 87))
        self.txt_signature.setObjectName("txt_signature")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(280, 390, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.btn_generate_keys = QtWidgets.QPushButton(self.centralwidget)
        self.btn_generate_keys.setGeometry(QtCore.QRect(610, 50, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_generate_keys.setFont(font)
        self.btn_generate_keys.setObjectName("btn_generate_keys")
        self.btn_verify = QtWidgets.QPushButton(self.centralwidget)
        self.btn_verify.setGeometry(QtCore.QRect(560, 390, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_verify.setFont(font)
        self.btn_verify.setObjectName("btn_verify")
        btn_sign.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(btn_sign)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 937, 26))
        self.menubar.setObjectName("menubar")
        btn_sign.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(btn_sign)
        self.statusbar.setObjectName("statusbar")
        btn_sign.setStatusBar(self.statusbar)

        self.retranslateUi(btn_sign)
        QtCore.QMetaObject.connectSlotsByName(btn_sign)

    def retranslateUi(self, btn_sign):
        _translate = QtCore.QCoreApplication.translate
        btn_sign.setWindowTitle(_translate("btn_sign", "MainWindow"))
        self.label_2.setText(_translate("btn_sign", "ECC CIPHER "))
        self.label_3.setText(_translate("btn_sign", "INFORMATION "))
        self.label_4.setText(_translate("btn_sign", "SIGNATURE"))
        self.pushButton.setText(_translate("btn_sign", "SIGN"))
        self.btn_generate_keys.setText(_translate("btn_sign", "GENERATE KEYS"))
        self.btn_verify.setText(_translate("btn_sign", "VERIFY"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    btn_sign = QtWidgets.QMainWindow()
    ui = Ui_btn_sign()
    ui.setupUi(btn_sign)
    btn_sign.show()
    sys.exit(app.exec_())
